# Filename: leo-routing-simu/tests/examples/test_pkl_output_format.py
# Tests PKL format with EMBEDDED static data in metadata

import unittest
import pickle
import os
import sys
from collections.abc import Mapping, Sequence

# --- Configuration ---
# Point to the PKL file that contains embedded data
# This should match the output filename used in the updated run_starlink_plane_many_gs.py
PKL_FILENAME = "starlink_many_gs_results_with_metadata.pkl"  # <<< CHECK THIS FILENAME
# --- End Configuration ---


class TestPklOutputFormatWithEmbeddedData(unittest.TestCase):
    """
    Tests the structure and basic format of the PKL file generated by
    simulation runner scripts that save EMBEDDED static data in metadata.
    """

    @classmethod
    def setUpClass(cls):
        """Load the PKL file once."""
        cls.pkl_data = None
        cls.pkl_load_error = None

        try:
            test_file_dir = os.path.dirname(os.path.abspath(__file__))
            project_root = os.path.abspath(os.path.join(test_file_dir, "..", ".."))
        except NameError:
            project_root = os.path.abspath(".")

        cls.pkl_file_path = os.path.join(project_root, PKL_FILENAME)

        print(
            f"\n[Test Setup] Attempting to load PKL file: {cls.pkl_file_path}"
        )  # Log attempt path
        if not os.path.exists(cls.pkl_file_path):
            cls.pkl_load_error = FileNotFoundError(
                f"PKL file not found: {cls.pkl_file_path}. Run the simulation script first to generate it."
            )
            print(f"[Test Setup] ERROR: {cls.pkl_load_error}")
            return

        try:
            with open(cls.pkl_file_path, "rb") as f:
                cls.pkl_data = pickle.load(f)
            print("[Test Setup] PKL file loaded successfully.")
        except Exception as e:
            cls.pkl_load_error = e
            print(f"[Test Setup] ERROR: Failed to load PKL file {cls.pkl_file_path}: {e}")

    def setUp(self):
        """Skip tests if PKL loading failed."""
        if self.pkl_load_error:
            self.skipTest(f"Skipping test: {self.pkl_load_error}")
        if self.pkl_data is None:
            self.skipTest(f"Skipping test: PKL data not loaded from {self.pkl_file_path}")

    def test_pkl_is_dictionary(self):
        """Verify the loaded PKL content is a dictionary."""
        self.assertIsInstance(self.pkl_data, dict)

    def test_pkl_has_top_level_keys(self):
        """Verify the dictionary has 'metadata' and 'time_step_data' keys."""
        self.assertIn("metadata", self.pkl_data)
        self.assertIn("time_step_data", self.pkl_data)

    def test_metadata_structure_and_embedded_data(self):
        """Verify the structure and presence/type of embedded data in metadata."""
        metadata = self.pkl_data["metadata"]
        self.assertIsInstance(metadata, dict, "'metadata' should be a dictionary.")

        # --- Check for EMBEDDED static data ---
        self.assertIn("tles_used", metadata)
        self.assertIsInstance(metadata["tles_used"], list)
        if metadata["tles_used"]:
            self.assertIsInstance(metadata["tles_used"][0], tuple)
            self.assertEqual(len(metadata["tles_used"][0]), 3)

        self.assertIn("ground_station_defs", metadata)
        self.assertIsInstance(metadata["ground_station_defs"], list)
        if metadata["ground_station_defs"]:
            self.assertIsInstance(metadata["ground_station_defs"][0], dict)
            self.assertIn("name", metadata["ground_station_defs"][0])
            self.assertIn("lat", metadata["ground_station_defs"][0])
            self.assertIn("lon", metadata["ground_station_defs"][0])
            self.assertIn("elv", metadata["ground_station_defs"][0])

        # Ensure key name matches what run_starlink_plane_many_gs saves ('isls')
        self.assertIn("isls", metadata)
        self.assertIsInstance(metadata["isls"], list)
        if metadata["isls"]:
            self.assertIsInstance(metadata["isls"][0], tuple)
            self.assertEqual(len(metadata["isls"][0]), 2)

        self.assertIn("max_gsl_length_m", metadata)
        self.assertTrue(isinstance(metadata["max_gsl_length_m"], (int, float)))
        self.assertIn("max_isl_length_m", metadata)
        self.assertTrue(isinstance(metadata["max_isl_length_m"], (int, float)))

        # --- Check other metadata keys ---
        self.assertIn("fstate_data_format", metadata)
        self.assertIsInstance(metadata["fstate_data_format"], str)
        self.assertEqual(metadata.get("fstate_data_format"), "dict_tuple_nh_if1_if2")
        self.assertIn("fstate_data_key", metadata)
        self.assertIsInstance(metadata["fstate_data_key"], str)
        self.assertEqual(metadata.get("fstate_data_key"), "fstate")
        self.assertIn("generation_time_utc", metadata)
        self.assertIsInstance(metadata["generation_time_utc"], str)
        self.assertIn("num_satellites", metadata)
        self.assertIsInstance(metadata["num_satellites"], int)
        self.assertIn("num_ground_stations", metadata)
        self.assertIsInstance(metadata["num_ground_stations"], int)

        # --- Check that path keys are ABSENT ---
        self.assertNotIn("source_simulation_setup_dir", metadata)
        self.assertNotIn("tles_file_name", metadata)

    def test_time_step_data_structure(self):
        """Verify the structure and basic types within time_step_data."""
        time_step_data = self.pkl_data["time_step_data"]
        self.assertIsInstance(time_step_data, list)

        if not time_step_data:
            print(f"Warning: 'time_step_data' is empty.")
            return
        first_step = None
        for step in time_step_data:
            if step is not None:
                first_step = step
                break
        if first_step is None:
            print(f"Warning: 'time_step_data' contains only None values.")
            return

        self.assertIsInstance(first_step, dict)
        self.assertIn("time_since_epoch_ns", first_step)
        self.assertIsInstance(first_step["time_since_epoch_ns"], int)
        # self.assertIn('bandwidth', first_step); self.assertIsInstance(first_step['bandwidth'], dict) # Optional: check other keys if needed

        fstate_key = self.pkl_data["metadata"].get("fstate_data_key", "fstate")
        self.assertIn(fstate_key, first_step)
        expected_format = self.pkl_data["metadata"].get(
            "fstate_data_format", "dict_tuple_nh_if1_if2"
        )
        fstate_actual_data = first_step[fstate_key]

        if expected_format == "dict_tuple_nh_if1_if2":
            self.assertIsInstance(fstate_actual_data, dict)
            if fstate_actual_data:
                first_fstate_key = next(iter(fstate_actual_data))
                first_fstate_value = fstate_actual_data[first_fstate_key]
                self.assertIsInstance(first_fstate_key, tuple)
                self.assertEqual(len(first_fstate_key), 2)
                self.assertIsInstance(first_fstate_value, tuple)
                self.assertEqual(len(first_fstate_value), 3)
                self.assertTrue(isinstance(first_fstate_value[0], int))
        else:
            self.fail(f"Test logic not implemented for fstate format: '{expected_format}'")


if __name__ == "__main__":
    unittest.main()
